# Generated by Django 3.2.4 on 2021-06-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text="Unique identifier for the given card, the result of 'blipping' it.", max_length=128, unique=True, verbose_name='Unique identifier')),
                ('owner', models.CharField(help_text='Who the card belongs to', max_length=128, verbose_name='Owner')),
                ('phone_number', models.CharField(help_text="Phone number belonging to the card's owner.", max_length=20, verbose_name='Phone number')),
                ('created', models.DateTimeField(help_text='When the card was added. This value is automatically updated.', verbose_name='Creation date')),
                ('modified', models.DateTimeField(help_text='When the card was last modified in some way.\n         This value is automatically updated.', verbose_name='Last modified')),
                ('valid_subscription', models.BooleanField(help_text='Whether or not the card has an activate subscription.', verbose_name='Subscription valid')),
                ('subscription_end', models.DateTimeField(help_text='When the subscription ends.', verbose_name='Subscription end')),
            ],
        ),
        migrations.CreateModel(
            name='uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('card', models.ForeignKey(help_text='The card used.', on_delete=django.db.models.deletion.CASCADE, to='backend.card', verbose_name='Card identifier')),
            ],
        ),
    ]
