# Generated by Django 3.2.4 on 2021-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='subscription_end',
            field=models.DateTimeField(blank=True, help_text='When the subscription ends.', null=True, verbose_name='Subscription end'),
        ),
    ]
